"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Sparkles, ShieldCheck, AlertTriangle, Rocket, Scale, Banknote, Wand2, Loader2 } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

interface Analysis {
  businessOverview: string;
  competitiveAdvantages: string[];
  risks: string[];
  growthDrivers: string[];
  financialStrength: string;
  valuationCommentary: string;
}

export function CompanyAI({ symbol, name }: { symbol: string; name: string }) {
  const [started, setStarted] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ["company-ai", symbol],
    queryFn: async (): Promise<{ available: boolean; data?: Analysis }> => {
      const res = await fetch(`/api/company-summary/${symbol}?name=${encodeURIComponent(name)}`);
      return res.json();
    },
    enabled: started, // only runs after the user clicks Generate
    staleTime: 60 * 60 * 1000,
    retry: false,
  });

  const header = (
    <div className="flex items-center gap-2 border-b border-border px-4 py-2.5 text-sm font-semibold">
      <Sparkles className="h-4 w-4 text-accent" /> AI Analysis
      <span className="ml-auto text-[10px] font-normal text-muted">Claude · Opus 4.8</span>
    </div>
  );

  // Not started → call-to-action (don't auto-spend on every page load)
  if (!started) {
    return (
      <Card className="overflow-hidden">
        {header}
        <CardContent className="flex flex-col items-center gap-4 p-6 text-center sm:flex-row sm:text-left">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-accent/10">
            <Wand2 className="h-5 w-5 text-accent" />
          </div>
          <p className="flex-1 text-sm text-muted">
            Generate an AI breakdown of <span className="font-medium text-foreground">{name}</span> — business
            overview, competitive moat, risks, growth drivers and valuation.
          </p>
          <button
            onClick={() => setStarted(true)}
            className="flex shrink-0 items-center gap-2 rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-black transition-colors hover:bg-accent-dim active:scale-[0.98]"
          >
            <Wand2 className="h-4 w-4" /> Generate analysis
          </button>
        </CardContent>
      </Card>
    );
  }

  if (isLoading) {
    return (
      <Card className="overflow-hidden">
        {header}
        <CardContent className="flex items-center gap-3 p-5 text-sm text-muted">
          <Loader2 className="h-4 w-4 animate-spin text-accent" />
          Analyzing {name} with Claude…
          <div className="ml-2 flex-1 space-y-2">
            <Skeleton className="h-3 w-full" />
            <Skeleton className="h-3 w-2/3" />
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!data?.available || !data.data) {
    return (
      <Card className="overflow-hidden">
        {header}
        <CardContent className="p-5 text-sm text-muted">
          AI company analysis is generated by Claude. Set <code className="rounded bg-surface px-1.5 py-0.5 text-xs text-foreground">ANTHROPIC_API_KEY</code> in{" "}
          <code className="rounded bg-surface px-1.5 py-0.5 text-xs text-foreground">.env.local</code> to enable
          auto-generated overviews, moats, risks, growth drivers and valuation commentary for every company.
        </CardContent>
      </Card>
    );
  }

  const a = data.data;
  return (
    <Card className="overflow-hidden">
      {header}
      <CardContent className="space-y-4 p-5">
        <p className="text-sm leading-relaxed text-muted">{a.businessOverview}</p>

        <div className="grid gap-4 sm:grid-cols-2">
          <List icon={ShieldCheck} color="text-positive" title="Competitive Advantages" items={a.competitiveAdvantages} />
          <List icon={AlertTriangle} color="text-warning" title="Key Risks" items={a.risks} />
          <List icon={Rocket} color="text-info" title="Growth Drivers" items={a.growthDrivers} />
          <div className="space-y-3">
            <Block icon={Banknote} color="text-positive" title="Financial Strength" text={a.financialStrength} />
            <Block icon={Scale} color="text-accent" title="Valuation" text={a.valuationCommentary} />
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

function List({
  icon: Icon,
  color,
  title,
  items,
}: {
  icon: typeof ShieldCheck;
  color: string;
  title: string;
  items: string[];
}) {
  return (
    <div>
      <h4 className={`mb-2 flex items-center gap-1.5 text-xs font-semibold ${color}`}>
        <Icon className="h-3.5 w-3.5" /> {title}
      </h4>
      <ul className="space-y-1.5">
        {items.map((t, i) => (
          <li key={i} className="flex gap-2 text-sm text-muted">
            <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-muted" />
            {t}
          </li>
        ))}
      </ul>
    </div>
  );
}

function Block({
  icon: Icon,
  color,
  title,
  text,
}: {
  icon: typeof ShieldCheck;
  color: string;
  title: string;
  text: string;
}) {
  return (
    <div className="rounded-lg bg-surface p-3">
      <h4 className={`mb-1 flex items-center gap-1.5 text-xs font-semibold ${color}`}>
        <Icon className="h-3.5 w-3.5" /> {title}
      </h4>
      <p className="text-sm leading-relaxed text-muted">{text}</p>
    </div>
  );
}
