"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import {
  Microscope, Search, Clock, Copy, Check, Loader2,
  Building2, Globe, Users, CalendarDays, ChevronRight,
  TrendingUp, Shield, Package, Network, Newspaper,
  FileText, FlaskConical, BarChart3, AlertTriangle,
} from "lucide-react";
import type { ResearchData } from "@/app/api/research/[query]/route";
import { LogoBadge } from "@/components/ui/logo-badge";
import { cn, colorFromString } from "@/lib/utils";
import {
  OverviewSection,
  LeadershipSection,
  TimelineSection,
  FinancialsSection,
  NewsSection,
  ProductsSection,
  CompetitorsSection,
  RisksSection,
  PatentsMarketSection,
  SocialSection,
  SummarySection,
} from "./research-sections";

/* ─────────────────────── Constants ──────────────────────────── */

const POPULAR = [
  { label: "NVIDIA", q: "NVDA" },
  { label: "Apple", q: "AAPL" },
  { label: "Tesla", q: "TSLA" },
  { label: "OpenAI", q: "OpenAI" },
  { label: "SpaceX", q: "SpaceX" },
  { label: "Stripe", q: "Stripe" },
  { label: "Meta", q: "META" },
  { label: "Revolut", q: "Revolut" },
];

const LOADING_MSGS = [
  "Identifying company profile...",
  "Searching financial databases...",
  "Analysing leadership team...",
  "Researching market position...",
  "Gathering competitive intelligence...",
  "Checking risks and regulatory filings...",
  "Scanning recent news...",
  "Synthesising intelligence report...",
];

const SECTIONS = [
  { id: "overview",     label: "Overview",     icon: Building2 },
  { id: "leadership",   label: "Leadership",   icon: Users },
  { id: "timeline",     label: "Timeline",     icon: CalendarDays },
  { id: "financials",   label: "Financials",   icon: BarChart3 },
  { id: "news",         label: "News",         icon: Newspaper },
  { id: "products",     label: "Products",     icon: Package },
  { id: "competitors",  label: "Competitors",  icon: Network },
  { id: "risks",        label: "Risks",        icon: AlertTriangle },
  { id: "patents",      label: "Patents",      icon: FlaskConical },
  { id: "social",       label: "Social",       icon: Globe },
  { id: "summary",      label: "Summary",      icon: FileText },
];

/* ─────────────────── localStorage history ───────────────────── */

const HISTORY_KEY = "alphaedge_research_history";
function getHistory(): string[] {
  try { return JSON.parse(localStorage.getItem(HISTORY_KEY) ?? "[]"); } catch { return []; }
}
function pushHistory(q: string) {
  try {
    const h = [q, ...getHistory().filter((x) => x.toLowerCase() !== q.toLowerCase())].slice(0, 8);
    localStorage.setItem(HISTORY_KEY, JSON.stringify(h));
  } catch { /* noop */ }
}

/* ────────────────── Markdown export helper ──────────────────── */

function toMarkdown(d: ResearchData): string {
  const c = d.company;
  const lines: string[] = [
    `# ${c.name}${c.ticker ? ` (${c.ticker})` : ""} — Company Intelligence Report`,
    `*Generated by AlphaEdge Research · ${new Date(d.generatedAt).toLocaleDateString()}*`,
    "",
    `## Overview`,
    `- **Type:** ${c.type}${c.exchange ? ` · ${c.exchange}` : ""}`,
    `- **Industry:** ${c.industry} · ${c.sector}`,
    `- **HQ:** ${c.hq}`,
    `- **Founded:** ${c.founded}`,
    `- **Employees:** ${c.employees}`,
    `- **Website:** ${c.website}`,
    "",
    c.description,
    "",
    `## Leadership`,
    ...d.leadership.map((l) => [`### ${l.name} — ${l.role}`, l.bio, l.achievements.length ? `**Key achievements:** ${l.achievements.join(", ")}` : ""].join("\n")),
    "",
    `## Company Timeline`,
    ...d.timeline.map((t) => `- **${t.year}** — ${t.event}`),
    "",
    `## Financials`,
    d.funding.marketCap ? `- **Market Cap:** ${d.funding.marketCap}` : "",
    d.funding.enterpriseValue ? `- **Enterprise Value:** ${d.funding.enterpriseValue}` : "",
    d.funding.totalRaised ? `- **Total Raised:** ${d.funding.totalRaised}` : "",
    d.funding.latestValuation ? `- **Latest Valuation:** ${d.funding.latestValuation}` : "",
    "",
    `## Products & Services`,
    ...d.products.map((p) => `- **${p.name}** (${p.category}) — ${p.description}`),
    "",
    `## Competitors`,
    ...d.competitors.map((c) => `- **${c.name}**${c.ticker ? ` (${c.ticker})` : ""} [${c.type} · ${c.size}] — ${c.description}`),
    "",
    `## Risks & Red Flags`,
    ...d.risks.map((r) => `- [${r.severity}] **${r.title}** (${r.category}) — ${r.description}`),
    "",
    `## Research Summary`,
    `### What They Do`, d.summary.what,
    `### Why It Matters`, d.summary.why,
    `### Strengths`, ...d.summary.strengths.map((s) => `- ${s}`),
    `### Weaknesses`, ...d.summary.weaknesses.map((s) => `- ${s}`),
    `### Opportunities`, ...d.summary.opportunities.map((s) => `- ${s}`),
    `### Key Risks`, ...d.summary.risks.map((s) => `- ${s}`),
    `### Recent Developments`, d.summary.developments,
  ];
  return lines.filter((l) => l !== null && l !== undefined).join("\n");
}

/* ──────────────────── Main component ───────────────────────── */

export function ResearchView() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const query = searchParams.get("q") ?? "";

  const [input, setInput] = useState(query);
  const [loadingMsgIdx, setLoadingMsgIdx] = useState(0);
  const [activeSection, setActiveSection] = useState("overview");
  const [copied, setCopied] = useState(false);
  const [history, setHistory] = useState<string[]>([]);
  const navRef = useRef<HTMLDivElement>(null);

  // ── Data fetching must come before any useEffect that references `data` ──
  const { data, isLoading, isError } = useQuery<ResearchData>({
    queryKey: ["research", query.toLowerCase().trim()],
    queryFn: async () => {
      const res = await fetch(`/api/research/${encodeURIComponent(query.trim())}`);
      if (!res.ok) throw new Error("Research failed");
      return res.json();
    },
    enabled: !!query.trim(),
    staleTime: 48 * 60 * 60 * 1000,
    retry: 1,
  });

  // Load history from localStorage on mount
  useEffect(() => { setHistory(getHistory()); }, []);

  // Cycle loading messages
  useEffect(() => {
    const id = setInterval(() => setLoadingMsgIdx((i) => (i + 1) % LOADING_MSGS.length), 3800);
    return () => clearInterval(id);
  }, []);

  // Sync input when URL changes
  useEffect(() => { setInput(query); }, [query]);

  // Scroll spy — re-registers once data arrives (sections not in DOM until then)
  useEffect(() => {
    if (!data) return;
    const obs = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) setActiveSection(e.target.id);
        });
      },
      { rootMargin: "-30% 0px -60% 0px" },
    );
    SECTIONS.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) obs.observe(el);
    });
    return () => obs.disconnect();
  }, [query, data]);

  const handleSearch = (q: string) => {
    const trimmed = q.trim();
    if (!trimmed) return;
    pushHistory(trimmed);
    setHistory(getHistory());
    router.push(`/research?q=${encodeURIComponent(trimmed)}`);
  };

  const scrollToSection = (id: string) => {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  const copyMarkdown = async () => {
    if (!data) return;
    await navigator.clipboard.writeText(toMarkdown(data));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  /* ── No query: show hero ── */
  if (!query) {
    return (
      <div className="flex min-h-[80vh] flex-col items-center justify-center px-4 py-12">
        <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-accent/10">
          <Microscope className="h-8 w-8 text-accent" />
        </div>
        <h1 className="mb-2 text-center text-3xl font-bold tracking-tight">
          Company Intelligence Research
        </h1>
        <p className="mb-8 max-w-lg text-center text-sm text-muted">
          Deep due-diligence on any public or private company — leadership, financials, risks,
          competitors, funding, patents and more. Powered by Claude AI.
        </p>

        {/* Search bar */}
        <form
          className="relative mb-6 w-full max-w-xl"
          onSubmit={(e) => { e.preventDefault(); handleSearch(input); }}
        >
          <Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted" />
          <input
            autoFocus
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Search by ticker, company name, domain…  e.g. NVDA, OpenAI, stripe.com"
            className="h-12 w-full rounded-xl border border-border bg-card pl-11 pr-28 text-sm shadow-premium focus:border-accent/50 focus:outline-none focus:shadow-glow-sm"
          />
          <button
            type="submit"
            className="absolute right-2 top-1/2 -translate-y-1/2 rounded-lg bg-accent px-4 py-1.5 text-sm font-semibold text-black transition-colors hover:bg-accent-dim"
          >
            Research
          </button>
        </form>

        {/* Popular */}
        <div className="mb-4 flex flex-wrap justify-center gap-2">
          {POPULAR.map(({ label, q }) => (
            <button
              key={q}
              onClick={() => handleSearch(q)}
              className="rounded-lg border border-border bg-card px-3 py-1.5 text-sm font-medium text-muted transition-colors hover:border-accent/40 hover:text-accent"
            >
              {label}
            </button>
          ))}
        </div>

        {/* Recent history */}
        {history.length > 0 && (
          <div className="mt-2 flex flex-wrap justify-center gap-2">
            <span className="text-xs text-muted flex items-center gap-1"><Clock className="h-3 w-3" /> Recent:</span>
            {history.slice(0, 5).map((h) => (
              <button
                key={h}
                onClick={() => handleSearch(h)}
                className="rounded-md bg-surface px-2.5 py-1 text-xs text-muted transition-colors hover:text-foreground"
              >
                {h}
              </button>
            ))}
          </div>
        )}

        {/* Feature highlights */}
        <div className="mt-12 grid max-w-2xl grid-cols-2 gap-3 sm:grid-cols-4">
          {[
            { icon: Users, label: "Leadership Profiles" },
            { icon: TrendingUp, label: "Funding & Financials" },
            { icon: Shield, label: "Risks & Red Flags" },
            { icon: Network, label: "Competitor Analysis" },
          ].map(({ icon: Icon, label }) => (
            <div key={label} className="flex flex-col items-center gap-2 rounded-xl border border-border bg-card p-4 text-center">
              <Icon className="h-5 w-5 text-accent" />
              <span className="text-xs font-medium">{label}</span>
            </div>
          ))}
        </div>
      </div>
    );
  }

  /* ── Has query: show results ── */
  return (
    <div className="mx-auto max-w-[1400px] px-4 py-5 sm:px-6">
      {/* Compact search bar */}
      <form
        className="relative mb-5 max-w-xl"
        onSubmit={(e) => { e.preventDefault(); handleSearch(input); }}
      >
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted" />
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Search another company…"
          className="h-9 w-full rounded-lg border border-border bg-card pl-9 pr-24 text-sm focus:border-accent/50 focus:outline-none"
        />
        <button
          type="submit"
          className="absolute right-2 top-1/2 -translate-y-1/2 rounded-md bg-accent px-3 py-1 text-xs font-semibold text-black hover:bg-accent-dim"
        >
          Research
        </button>
      </form>

      {/* Loading state */}
      {isLoading && (
        <div className="flex flex-col items-center justify-center py-24">
          <div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-accent/10">
            <Loader2 className="h-7 w-7 animate-spin text-accent" />
          </div>
          <p className="text-base font-semibold">{LOADING_MSGS[loadingMsgIdx]}</p>
          <p className="mt-1 text-sm text-muted">
            Claude is conducting deep research on <span className="font-medium text-foreground">{query}</span>
          </p>
          <div className="mt-6 flex gap-1.5">
            {LOADING_MSGS.map((_, i) => (
              <span
                key={i}
                className={cn(
                  "h-1 rounded-full transition-all",
                  i === loadingMsgIdx ? "w-6 bg-accent" : "w-1.5 bg-border",
                )}
              />
            ))}
          </div>
        </div>
      )}

      {/* Error state */}
      {isError && !isLoading && (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <AlertTriangle className="mb-3 h-8 w-8 text-negative" />
          <p className="font-semibold">Research failed</p>
          <p className="mt-1 text-sm text-muted">The AI couldn't complete this research. Try again or search a different company.</p>
          <button
            onClick={() => router.refresh()}
            className="mt-4 rounded-lg bg-card px-4 py-2 text-sm border border-border hover:border-accent/40"
          >
            Retry
          </button>
        </div>
      )}

      {/* Results */}
      {data && !isLoading && (
        <>
          {/* Company header */}
          <CompanyHeader data={data} onCopy={copyMarkdown} copied={copied} />

          {/* Sticky section nav */}
          <div
            ref={navRef}
            className="sticky top-0 z-30 -mx-4 mb-6 overflow-x-auto border-b border-border bg-background/90 backdrop-blur-lg px-4 sm:-mx-6 sm:px-6"
          >
            <div className="flex min-w-max gap-0.5 py-1">
              {SECTIONS.map(({ id, label, icon: Icon }) => (
                <button
                  key={id}
                  onClick={() => scrollToSection(id)}
                  className={cn(
                    "flex items-center gap-1.5 rounded-md px-3 py-2 text-xs font-medium transition-colors whitespace-nowrap",
                    activeSection === id
                      ? "bg-accent/10 text-accent"
                      : "text-muted hover:bg-card hover:text-foreground",
                  )}
                >
                  <Icon className="h-3.5 w-3.5" />
                  {label}
                </button>
              ))}
            </div>
          </div>

          {/* All sections */}
          <div className="space-y-6">
            <OverviewSection data={data} />
            <LeadershipSection data={data} />
            <TimelineSection data={data} />
            <FinancialsSection data={data} />
            <NewsSection data={data} />
            <ProductsSection data={data} />
            <CompetitorsSection data={data} />
            <RisksSection data={data} />
            <PatentsMarketSection data={data} />
            <SocialSection data={data} />
            <SummarySection data={data} />
          </div>
        </>
      )}
    </div>
  );
}

/* ─────────────── Company Header ─────────────────────────────── */

function CompanyHeader({
  data,
  onCopy,
  copied,
}: {
  data: ResearchData;
  onCopy: () => void;
  copied: boolean;
}) {
  const c = data.company;
  return (
    <div className="mb-5 rounded-xl border border-border bg-card p-4 sm:p-5">
      <div className="flex flex-wrap items-start gap-4">
        {/* Logo */}
        <div className="shrink-0">
          <LogoBadge symbol={c.ticker ?? c.name} color={colorFromString(c.name)} size={52} />
        </div>

        {/* Identity */}
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-xl font-bold">{c.name}</h1>
            {c.ticker && (
              <span className="rounded-md bg-accent/10 px-2 py-0.5 text-xs font-semibold text-accent">
                {c.ticker}
              </span>
            )}
            {c.exchange && (
              <span className="rounded-md bg-surface px-2 py-0.5 text-xs text-muted">
                {c.exchange}
              </span>
            )}
            <span
              className={cn(
                "rounded-md px-2 py-0.5 text-xs font-medium",
                c.type === "Public"
                  ? "bg-positive/10 text-positive"
                  : "bg-info/10 text-info",
              )}
            >
              {c.type}
            </span>
          </div>

          {/* Meta row */}
          <div className="mt-1.5 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted">
            {c.industry !== "Unknown" && (
              <span className="flex items-center gap-1">
                <Building2 className="h-3 w-3" /> {c.industry}
              </span>
            )}
            {c.hq !== "Unknown" && (
              <span className="flex items-center gap-1">
                <Globe className="h-3 w-3" /> {c.hq}
              </span>
            )}
            {c.founded !== "Unknown" && (
              <span className="flex items-center gap-1">
                <CalendarDays className="h-3 w-3" /> Founded {c.founded}
              </span>
            )}
            {c.employees !== "Unknown" && (
              <span className="flex items-center gap-1">
                <Users className="h-3 w-3" /> {c.employees} employees
              </span>
            )}
            {c.website && (
              <a
                href={c.website.startsWith("http") ? c.website : `https://${c.website}`}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1 transition-colors hover:text-accent"
              >
                <Globe className="h-3 w-3" /> {c.website.replace(/^https?:\/\//, "")}
                <ChevronRight className="h-3 w-3" />
              </a>
            )}
          </div>

          {/* Quick financial pills */}
          {(data.funding.marketCap || data.funding.latestValuation || data.funding.totalRaised) && (
            <div className="mt-2 flex flex-wrap gap-2">
              {data.funding.marketCap && (
                <Pill label="Market Cap" value={data.funding.marketCap} />
              )}
              {data.funding.enterpriseValue && (
                <Pill label="EV" value={data.funding.enterpriseValue} />
              )}
              {data.funding.latestValuation && (
                <Pill label="Valuation" value={data.funding.latestValuation} />
              )}
              {data.funding.totalRaised && (
                <Pill label="Total Raised" value={data.funding.totalRaised} />
              )}
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="flex shrink-0 items-start gap-2">
          <button
            onClick={onCopy}
            className="flex items-center gap-1.5 rounded-lg border border-border bg-surface px-3 py-1.5 text-xs font-medium text-muted transition-colors hover:border-accent/40 hover:text-accent"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-positive" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied!" : "Copy Report"}
          </button>
        </div>
      </div>
    </div>
  );
}

function Pill({ label, value }: { label: string; value: string }) {
  return (
    <span className="flex items-baseline gap-1 rounded-md bg-surface px-2.5 py-1 text-xs">
      <span className="text-muted">{label}</span>
      <span className="font-semibold">{value}</span>
    </span>
  );
}
